name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x]

    steps:
    - uses: actions/checkout@v6
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    # pnpm ci doesn't exist, pnpm install works close enough
    - run: pnpm install
    # Run an audit check, and fail if any moderate+ vulnerabilities arise
    - run: pnpm audit --audit-level=moderate